### ISSUE TITLE
IMP: Nested Related Data no longer displays in the ancestor form

### ISSUE THREAD

**Issue by pxslip** [pxslip/db-studio#5]
```
GrandParent --> Parent --> Child
```

In the `Grandparent` form, the data from `Child` shows as `--`

**Comment by Dumpstar56** [comment]
In the Grandparent form, the data from Child shows as --, if the Child has m2m relationship to the parent. Likely this is related to the fact that the field could then display multiple values. In V10, these are displayed as [value 1; value 2...].
